language: android

android:
  components:
    - build-tools-21.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21

branches:
  except:
    - gh-pages

script:
 - ./gradlew clean check
